services:
  artc-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artc-service
    ports:
      - "9876:9876"
    volumes:
      - ./videos:/app/videos
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
